/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'sans': ['Inter', 'system-ui', 'sans-serif'],
        'bold': ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        'bg': '#1a1a1a',
        'surface-0': '#2a2a2a',
        'surface-1': '#333333',
        'surface-2': '#404040',
        'border-outline': '#4a4a4a',
        'text-primary': '#ffffff',
        'text-secondary': '#cccccc',
        'text-muted': '#999999',
        'text-inverse': '#ffffff',
        'accent-red': '#e74c3c',
        'accent-red-pressed': '#c0392b',
        'accent-red-border': '#a93226',
        'price-text': '#e0e0e0',
        'icon-mono': '#ffffff',
        'disabled': '#666666',
        'shadow': 'rgba(0,0,0,0.5)',
        'surface-hover': '#404040',
        'surface-selected': '#c0392b',
        'accent-primary': '#e74c3c',
        'accent-secondary': '#c0392b',
        'accent-danger': '#e74c3c',
        'accent-close': '#e74c3c',
        'header': '#2a2a2a',
        'premium-bg': '#1B1E24',
        'premium-surface-0': '#23272F',
        'premium-surface-1': '#2B3038',
        'premium-surface-2': '#323844',
        'premium-border-outline': '#3A404A',
        'premium-text-primary': '#F3F5F7',
        'premium-text-secondary': '#C3C9D4',
        'premium-text-muted': '#8A93A3',
        'premium-text-inverse': '#ffffff',
        'premium-accent-red': '#FF4D4F',
        'premium-accent-red-pressed': '#E04345',
        'premium-accent-red-border': '#B83739',
        'premium-price-text': '#F3F5F7',
        'premium-icon-mono': '#F3F5F7',
        'premium-disabled': '#6B7280',
        'premium-shadow': 'rgba(0,0,0,0.3)',
        'premium-surface-hover': '#323844',
        'premium-surface-selected': '#E04345',
        'premium-accent-primary': '#FF4D4F',
        'premium-accent-secondary': '#F5A524',
        'premium-accent-danger': '#FF4D4F',
        'premium-accent-close': '#FF4D4F',
        'premium-header': '#23272F',
      },
      borderRadius: {
        'card': '4px',
        'input': '4px',
        'pill': '4px',
        'premium-card': '6px',
        'premium-input': '4px',
        'premium-pill': '6px',
      },
      animation: {
        'fade-in': 'fadeIn 150ms ease-in-out',
        'slide-up': 'slideUp 200ms ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
      boxShadow: {
        'card': '0 4px 6px -1px rgba(0,0,0,0.38), 0 2px 4px -1px rgba(0,0,0,0.25)',
        'card-hover': '0 10px 15px -3px rgba(0,0,0,0.38), 0 4px 6px -2px rgba(0,0,0,0.25)',
      }
    },
  },
  plugins: [],
}
